### ISSUE TITLE
Get value of axis after drag

### ISSUE THREAD

**Issue by felipeucd** [mmihira/d3-radarchart#1]
Hi. 
Could you advise how can I get the new value of an axis after dragging it on the screen?
I would like to get this new value to update a table of calculations using the radar graph as a weighting component.
The component is great.
Thank you.

**Comment by mmihira** [comment]
Hey, thanks for using it !

You can use the `onValueChange` option to get the properties of the change.
Example is here : https://codesandbox.io/s/react-example-vvzbh?fontsize=14

**Comment by felipeucd** [comment]
That's great! Thanks for the example.
